#+TITLE: git


*** Undo

- How can I undo changes to unstaged files?

#+BEGIN_SRC bash
git checkout -- <filename>
#+END_SRC

- How can I unstage a file that I have staged?

#+BEGIN_SRC bash
git reset HEAD <filename>
#+END_SRC

- How do I restore an old version of a file?

#+BEGIN_SRC bash
git checkout <first-six-hash-characters> <filename>
#+END_SRC

- How do I undo all of the changes I have made?

#+BEGIN_SRC bash
git reset HEAD <directory1> [<directory2> ...]
git reset HEAD <filename1> [<filename2> ...]
#+END_SRC

#+BEGIN_SRC bash
git checkout -- <directory1> [<directory2> ...]
git checkout -- <filename1> [<filename2> ...]
#+END_SRC


*** Branch


- How can I see what branches my repository has?

#+BEGIN_SRC bash
git branch
#+END_SRC

- How can I view the differences between branches?

#+BEGIN_SRC bash
git diff <branch-1>..<branch-2>
#+END_SRC

Note: there's two dots between branch names

- How can I switch from one branch to another?

#+BEGIN_SRC bash
git checkout <branch-name>
#+END_SRC

- How can I create a branch?

#+BEGIN_SRC bash
git checkout -b <branch-name>
#+END_SRC

- How can I merge two branches?

#+BEGIN_SRC bash
git merge <source> <destination>
#+END_SRC

- How can I merge two branches with conflicts?

- How can I delete a branch?

#+BEGIN_SRC bash
git branch -d <branch-name>
#+END_SRC

- How do I create a tag?

#+BEGIN_SRC bash
git tag <semantic-version> <first-10-character-commit-id>
#+END_SRC

*** Collaborating

- How can I create a brand new repository?

#+BEGIN_SRC bash
git init <project-name>
#+END_SRC

- How can I turn an existing project into a Git repository?

#+BEGIN_SRC bash
git init <path/to/project>
#+END_SRC

- How can I create a copy of an existing repository?

#+BEGIN_SRC bash
git clone <URL>
# or from local project
git clonet <file:///existing/project> <new-project-name>
#+END_SRC

- How can I find out where a cloned repository originated?

#+BEGIN_SRC bash
git remote
git remove -v
#+END_SRC

- How can I define remotes?

#+BEGIN_SRC bash
git remote add <remote-name> <URL>
#+END_SRC

Remove remote:

#+BEGIN_SRC bash
git remote rm <remote-name>
#+END_SRC

- How can I pull in changes from a remote repository?

#+BEGIN_SRC bash
git pull <remote-name> <branch-name>
#+END_SRC

- What happens if I try to pull when I have unsaved changes?

Either commit your local changes or revert them, then try to pull again.

- How can I push my changes to a remote repository?

#+BEGIN_SRC bash
git push <remote-name> <branch-name>
#+END_SRC

- What happens if my push conflicts with someone else's work?

To prevent this happening, Git does not allow you to push changes to a remote
repository unless you have merged the contents of the remote repository into
your own work.

*** References

- https://www.atlassian.com/git/tutorials
- https://www.tutorialspoint.com/git/index.htm
- https://jwiegley.github.io/git-from-the-bottom-up/ by legendary John Wiegley
- https://chris.beams.io/posts/git-commit/ on how to write a good commit
- https://guides.github.com/introduction/flow/ on Github flow
- https://guides.github.com/activities/hello-world/ a simple example of Github flow
- http://rogerdudler.github.io/git-guide/ no shit guide for getting started with git
